[package]
name = "envjson"
version = "0.1.0"
authors = ["Diego Veralli <diegoov@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
opt-level = 's'